### PR TITLE
Upgrade to axe-core 3.4.0

### PR DESCRIPTION
**Pull request by gtritchie**
Might as well upgrade to the latest; had I known 3.4.0 was on the way wouldn't have bothered with 3.3.2!

### CODE REVIEW

**Comment by kimberlythegeek** [comment]
@gtritchie Thank you! Sorry for the delay, this is not actively being maintained, but I will do so in the next few weeks so it is up-to-date and stable. Looks like another PR has been file for axe version 4.0, so I will be likely be closing this PR and reviewing that one instead.

Expect an update within the next two weeks. Thank you again 🥰

**Comment by gtritchie** [comment]
@kimberlythegeek Awesome, thanks for the update. Will you be able to push up to the PyPI as well, that would be extra awesome!

**Comment by kimberlythegeek** [comment]
@gtritchie Yessir! I haven't touched this code and forever so it is in dire need 😅

**Comment by gtritchie** [comment]
> @gtritchie Yessir! I haven't touched this code and forever so it is in dire need 😅

Christmas is saved! (well, that might be a bit overly dramatic of me)

**Comment by kimberlythegeek** [comment]
Aplogies again-- :sweat_smile:  it seems this got away from me. Been a crazy few years :upside_down_face: 

Thank you for your contribution, it appears there is an open PR for a newer version of axe, so I will be closing this one.

**Pull request closed without merging**
