### PR TITLE
Added package.json file to maintain axe-core dependency

### PR DESCRIPTION
**Pull request by kimberlythegeek**
Will use npm to keep axe-core up to date, rather than doing so manually

fixed password hash for travis pypi deployment
moved changelog into readme to avoid file not found error

### CODE REVIEW

**Comment by kimberlythegeek** [comment]
@davehunt When the travis builds ran without it, the tests failed, because the axe-core javascript file was missing. I don't know exactly how to install npm dependencies and make sure they are in the correct directory. I'll look into it again this morning.

**Comment by davehunt** [comment]
Ah, maybe add an `npm install` command to `.travis.yml`?

**Comment by kimberlythegeek** [comment]
@davehunt I attempted to do that, but I really don't know enough about Docker. I'll have to read more documentation and give it another try. Too bad we're missing our Docker person :)

**Comment by davehunt** [comment]
Oh right, this is in Docker. Can you add node and the install command to the Docker image instead?

**Comment by kimberlythegeek** [comment]
@davehunt I attempted to do that, but I really don't know enough about Docker. I'll have to read more documentation and give it another try. Too bad we're missing our Docker person :)

**Pull request merged**
