### PR TITLE
[WIP] Fix Jenkins build by removing the removed-elsewhere Docker relics

### PR DESCRIPTION
**Pull request by stephendonner**
This isn't-yet ready - there are Docker-related build issues in Jenkins (qa-preprod) I'm working on fixing and will push soon (hopefully), here!

### CODE REVIEW

**Comment by stephendonner** [comment]
@davehunt if you're able to help with this, I'd greatly appreciate it.

All of the builds (master, PRs) for https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/axe-sel-python/ are still referencing/expecting the Dockerfile, which was removed over in https://github.com/mozilla-services/axe-selenium-python/commit/22a6e1e09a19b282b40729d81cec475c1baeb371#diff-3254677a7917c6c01f55212f86c57fbf

**Comment by kimberlythegeek** [comment]
@stephendonner With the tests running in Travis, perhaps we should just remove the Jenkins job altogether?

**Comment by stephendonner** [comment]
@kimberlythegeek sounds fine to me!  We should remove/decouple:

1. Jenkins/Jenkinsfile
2. Sauce Labs
3. Anything else?

**Comment by kimberlythegeek** [comment]
@stephendonner Nothing comes to mind; sounds good!

**Comment by kimberlythegeek** [comment]
Closing in favor of #137

**Pull request closed without merging**
